### ISSUE TITLE
Add a disclaimer in readme for bcode and G2/G3

### ISSUE THREAD

**Issue by devilzmods** [olistrik/goskew#9]
especially the bcode one threw me for a loop, even though it's obvious in hindsight.
Both are simple setting fixes, but hard to diagnose when simply nothing happens.

**Comment by olistrik** [comment]
![image](https://github.com/olistrik/goskew/assets/17579507/76b67249-e736-429f-b9d6-e3b8520f1408)

Done! I've added them to the prusaslicer section.
